// Owner keys for the Sarus parameter lock. Generated by the Sarus firmware's Tools/sarus/lock_keys.py
// (csharp command) from sarus-lock-keys.json; rerun it rather than editing this file. Salts and public keys
// are not secret. An empty list leaves the lock off, as before.
namespace MissionPlanner.ArduPilot
{
    internal static class SarusLockKeys
    {
        internal static readonly SarusLock.Key[] Owner =
        {
        };
    }
}
